// Mocks generated by Mockito 5.4.4 from annotations
// in dart_server/test/server_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:dart_server/models/response_owner.dart' as _i2;
import 'package:dart_server/repositories/owner_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseOwner_0 extends _i1.SmartFake implements _i2.ResponseOwner {
  _FakeResponseOwner_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OwnerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOwnerRepository extends _i1.Mock implements _i3.OwnerRepository {
  MockOwnerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseOwner getElementById({required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getElementById,
          [],
          {#id: id},
        ),
        returnValue: _FakeResponseOwner_0(
          this,
          Invocation.method(
            #getElementById,
            [],
            {#id: id},
          ),
        ),
      ) as _i2.ResponseOwner);

  @override
  _i2.ResponseOwner deserialize(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #deserialize,
          [json],
        ),
        returnValue: _FakeResponseOwner_0(
          this,
          Invocation.method(
            #deserialize,
            [json],
          ),
        ),
      ) as _i2.ResponseOwner);

  @override
  Map<String, dynamic> serialize(_i2.ResponseOwner? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #serialize,
          [item],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void readJsonFile(String? filePath) => super.noSuchMethod(
        Invocation.method(
          #readJsonFile,
          [filePath],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getListLength() => (super.noSuchMethod(
        Invocation.method(
          #getListLength,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void addToList({required _i2.ResponseOwner? item}) => super.noSuchMethod(
        Invocation.method(
          #addToList,
          [],
          {#item: item},
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.ResponseOwner> getList() => (super.noSuchMethod(
        Invocation.method(
          #getList,
          [],
        ),
        returnValue: <_i2.ResponseOwner>[],
      ) as List<_i2.ResponseOwner>);

  @override
  void update({
    required int? index,
    required _i2.ResponseOwner? item,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #index: index,
            #item: item,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void remove({required int? index}) => super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
          {#index: index},
        ),
        returnValueForMissingStub: null,
      );
}
