// Mocks generated by Mockito 5.4.4 from annotations
// in dart_server/test/server_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dart_server/db/database.dart' as _i2;
import 'package:dart_server/repositories/owner_repository.dart' as _i4;
import 'package:dart_shared/dart_shared.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeParkingDatabase_0 extends _i1.SmartFake
    implements _i2.ParkingDatabase {
  _FakeParkingDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOwner_1 extends _i1.SmartFake implements _i3.Owner {
  _FakeOwner_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OwnerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOwnerRepository extends _i1.Mock implements _i4.OwnerRepository {
  MockOwnerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ParkingDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeParkingDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.ParkingDatabase);

  @override
  void addToList({required dynamic json}) => super.noSuchMethod(
        Invocation.method(
          #addToList,
          [],
          {#json: json},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<Map<String, dynamic>>> getList() => (super.noSuchMethod(
        Invocation.method(
          #getList,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Owner deserialize(Map<String, dynamic>? json) => (super.noSuchMethod(
        Invocation.method(
          #deserialize,
          [json],
        ),
        returnValue: _FakeOwner_1(
          this,
          Invocation.method(
            #deserialize,
            [json],
          ),
        ),
      ) as _i3.Owner);

  @override
  Map<String, dynamic> serialize(_i2.DBOwner? item) => (super.noSuchMethod(
        Invocation.method(
          #serialize,
          [item],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  int getListLength() => (super.noSuchMethod(
        Invocation.method(
          #getListLength,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void update({
    required int? index,
    required _i3.Owner? item,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #index: index,
            #item: item,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void remove({required int? index}) => super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
          {#index: index},
        ),
        returnValueForMissingStub: null,
      );
}
