name: dart_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.0.6

dependencies:
  args: ^2.3.0
  intl: ^0.19.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  uuid: ^4.5.1
  drift: ^2.6.0
  sqlite3: ^2.0.0
  path: ^1.8.0
  dart_shared:
    path: "../dart_shared"

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
  mockito: ^5.0.8
  build_runner: ^2.0.4
  drift_dev: ^2.6.0
